# .github/workflows/pr-push.yml
name: CI
on:
  pull_request: {}
  push:
    branches: [gh-pages]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN }}
          W3C_WG_DECISION_URL: [replace with actual link to decision]
          W3C_BUILD_OVERRIDE: |
             shortName: fingerprinting-guidance
             specStatus: IG-NOTE
